### ISSUE TITLE
No communication

### ISSUE THREAD

**Issue by Ivohome** [MFxMF/SDM630-Modbus#1]
I can read the line voltages, but the phase currents and power are still 0, although on the SDM630 meter display it shows values. Do you have any clue what could be the mistake here?

**Comment by MFxMF** [comment]
Could you run debug mode and paste the result?

**Comment by Ivohome** [comment]
This weekend I finally got the time to completely install the meter in my home installation. To test the communication, I only connected 1 phase before. And that turned out to be the root cause. After connecting all 3 phases it works! I am very happy with the result, this is exactly what I was looking for for quite some time. Although I still cannot understand why it did not work for 1 phase only. Thanks for all your good work!
